#' Path to the outputs generated by the model
#'
#' @include enum.R
#' @export
OutputPaths <- enum(list(
  T3_PVB = "Organism|PeripheralVenousBlood|T3|Plasma (Peripheral Venous Blood)",
  T3_pitCell = "Organism|Brain|Pituitary|Intracellular|T3|Concentration",
  T4_PVB = "Organism|PeripheralVenousBlood|T4|Plasma (Peripheral Venous Blood)",
  TSH_PVB = "Organism|PeripheralVenousBlood|TSH|Plasma (Peripheral Venous Blood)",
  T3_VB = "Organism|VenousBlood|Plasma|T3|Concentration in container",
  T4_VB = "Organism|VenousBlood|Plasma|T4|Concentration in container",
  TSH_VB = "Organism|VenousBlood|Plasma|TSH|Concentration in container",
  T3_thyrInt = "Organism|Thyroid|Interstitial|T3|Concentration in container",
  T4_thyrInt = "Organism|Thyroid|Interstitial|T4|Concentration in container",
  TSH_thyrInt = "Organism|Thyroid|Interstitial|TSH|Concentration in container",
  T3_pitInt = "Organism|Brain|Pituitary|Interstitial|T3|Concentration in container",
  T4_pitInt = "Organism|Brain|Pituitary|Interstitial|T4|Concentration in container",
  TSH_pitInt = "Organism|Brain|Pituitary|Interstitial|TSH|Concentration in container",
  Perpetrator_VB = "Organism|VenousBlood|Plasma|Perpetrator|Concentration in container",
  PTU_VB = "Organism|VenousBlood|Plasma|PTU|Concentration in container",
  T3_synthesis_rate = "Organism|Thyroid|Plasma|T3_synthesis|ProcessRate",
  T4_DIO_rate = "Organism|**|T4-DIO-Human|ProcessRate",
  M_TSH_T4_sec = "Organism|Thyroid|Plasma|T4_synthesis|M_TSH"
))
